#!/usr/bin/env bash
# Stage 05 SLURM driver: run SourceCatalogStep on each mosaic.
#
# Builds a manifest of top-level coadds and submits one array task per line:
#   strun romancal.source_catalog.SourceCatalogStep <coadd> \
#       --output_dir <cat-dir> --save_results=true --npixels=$NPIXELS \
#       > <log> 2>&1
# wrapped with skip-if-exists.
#
# Env-var hooks:
#   SUBSET            sbatch --array spec, default "1-N"
#   MAX_CONCURRENT    --array=...%K, default 80 (5 mem-lg nodes x 16 cores; 8G mem fits)
#   PARTITION         default mem-lg
#   MEM               default 8G
#   TIME              default 30:00 (catalogs typ. 30s-3min)
#   NPIXELS           SourceCatalogStep --npixels, default 16 (per detection study)
#   LINE_OFFSET       added to SLURM_ARRAY_TASK_ID to pick the manifest line.
#                     Default 0. Use this to chunk arrays larger than the cluster's
#                     MaxArraySize (e.g. SUBSET=1-900 LINE_OFFSET=900 -> manifest lines 901-1800).
#
# Usage: slurm_run_catalog.sh configs/<tag>.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:?usage: $0 configs/<tag>.yaml}"
eval "$(pixi run python scripts/_config.py "$CONFIG")"

MOSAIC_DIR="${OUTPUT_BASE}/${TAG}/mosaic"
CAT_DIR="${OUTPUT_BASE}/${TAG}/catalog"
LOG_DIR="${OUTPUT_BASE}/logs"
META_DIR="${OUTPUT_BASE}/${TAG}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/catalog
mkdir -p "$CAT_DIR" "$LOG_DIR" "$META_DIR" "$SLURM_LOG"

[ -d "$MOSAIC_DIR" ] || { echo "missing $MOSAIC_DIR (run slurm_run_mosaic.sh first)"; exit 1; }

NPIXELS="${NPIXELS:-16}"

TS=$(date +%Y%m%dT%H%M%S)
MANIFEST="${META_DIR}/catalog_${TS}.manifest"
ls "$MOSAIC_DIR"/*_coadd.asdf 2>/dev/null | sort > "$MANIFEST"
N=$(wc -l < "$MANIFEST")
[ "$N" -gt 0 ] || { echo "no coadds in $MOSAIC_DIR"; exit 1; }

ARR="${SUBSET:-1-${N}}"
K="${MAX_CONCURRENT:-80}"
PART="${PARTITION:-mem-lg}"
MEM="${MEM:-8G}"
TIME="${TIME:-30:00}"
OFFSET="${LINE_OFFSET:-0}"

PROJ_ABS=$(pwd)

TASK_WRAPPER="${META_DIR}/_catalog_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_catalog.sh at $(date -Iseconds) for ${CONFIG} (${TAG}).
# One SLURM array task = one manifest line (line = TASK_ID + OFFSET).
set -euo pipefail
cd "${PROJ_ABS}"
LINE_NUM=\$((SLURM_ARRAY_TASK_ID + ${OFFSET}))
M=\$(sed -n "\${LINE_NUM}p" "${MANIFEST}")
[ -n "\$M" ] || { echo "empty manifest line at index \${LINE_NUM} (TASK_ID=\${SLURM_ARRAY_TASK_ID} OFFSET=${OFFSET})" >&2; exit 1; }
BASE=\$(basename "\$M" .asdf)
OUT="${CAT_DIR}/\${BASE%_coadd}_cat.parquet"
LOG="${LOG_DIR}/\${BASE%_coadd}_catalog.log"
if [ -f "\$OUT" ]; then
    echo "skip (exists): \$OUT"
    exit 0
fi
exec pixi run --manifest-path "${PROJ_ABS}/pixi.toml" bash -c "strun romancal.source_catalog.SourceCatalogStep \"\$M\" --output_dir \"${CAT_DIR}\" --save_results=true --npixels=${NPIXELS} > \"\$LOG\" 2>&1"
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --cpus-per-task=1 --mem="$MEM" --time="$TIME" \
    --array="${ARR}%${K}" --job-name=acc-catalog \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

META="${META_DIR}/catalog-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
cp "$MANIFEST"     "${META}.manifest"
{
    echo "JOB=$JOB"
    echo "ARRAY=$ARR"
    echo "LINE_OFFSET=$OFFSET"
    echo "MAX_CONCURRENT=$K"
    echo "PARTITION=$PART"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "NPIXELS=$NPIXELS"
    echo "CONFIG=$CONFIG"
    echo "MANIFEST=$MANIFEST"
    echo "MANIFEST_LINES=$N"
    echo "GIT_COMMIT=$(git -C "$PROJ_ABS" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array ${ARR}, K=${K}, partition=${PART}, mem=${MEM}, npixels=${NPIXELS})"
echo "  manifest:     ${MANIFEST} (${N} catalogs)"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler logs: ${SLURM_LOG}/${JOB}_*.out"
