#!/usr/bin/env bash
# Stage 04 SLURM driver: run MosaicPipeline on each surviving asn JSON.
#
# Builds a manifest of top-level asn JSONs (one per kept skycell; excludes
# the rejected/ subdir produced by filter_asn_skycells.py) and submits one
# array task per manifest line. Each task runs:
#   strun romancal.pipeline.MosaicPipeline <asn> --output_dir <mosaic-dir> \
#       --steps.resample.in_memory=False > <log> 2>&1
# wrapped with skip-if-exists.
#
# Env-var hooks:
#   SUBSET            sbatch --array spec, default "1-N" where N = manifest line count
#   MAX_CONCURRENT    --array=...%K, default 25 (5 mem-lg nodes; 24G mem-per-task fits ~5/node)
#   PARTITION         default mem-lg
#   MEM               default 24G  (largest per-resample buffer + headroom)
#   TIME              default 2:00:00 (mosaics typ. 5-15 min)
#   LINE_OFFSET       added to SLURM_ARRAY_TASK_ID to pick the manifest line.
#                     Default 0. Use this to chunk arrays larger than the cluster's
#                     MaxArraySize (e.g. SUBSET=1-900 LINE_OFFSET=900 -> manifest lines 901-1800).
#
# Usage: slurm_run_mosaic.sh configs/<tag>.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:?usage: $0 configs/<tag>.yaml}"
eval "$(pixi run python scripts/_config.py "$CONFIG")"

ASN_DIR="${OUTPUT_BASE}/${TAG}/asn"
MOSAIC_DIR="${OUTPUT_BASE}/${TAG}/mosaic"
LOG_DIR="${OUTPUT_BASE}/logs"
META_DIR="${OUTPUT_BASE}/${TAG}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/mosaic
mkdir -p "$MOSAIC_DIR" "$LOG_DIR" "$META_DIR" "$SLURM_LOG"

[ -d "$ASN_DIR" ] || { echo "missing $ASN_DIR (run 03_build_asn.sh + filter_asn_skycells.py first)"; exit 1; }

# Manifest: top-level asn JSONs only (excludes rejected/ subdir).
TS=$(date +%Y%m%dT%H%M%S)
MANIFEST="${META_DIR}/mosaic_${TS}.manifest"
ls "$ASN_DIR"/*_asn.json 2>/dev/null | sort > "$MANIFEST"
N=$(wc -l < "$MANIFEST")
[ "$N" -gt 0 ] || { echo "no asn JSONs in $ASN_DIR"; exit 1; }

ARR="${SUBSET:-1-${N}}"
K="${MAX_CONCURRENT:-25}"
PART="${PARTITION:-mem-lg}"
MEM="${MEM:-24G}"
TIME="${TIME:-2:00:00}"
OFFSET="${LINE_OFFSET:-0}"

PROJ_ABS=$(pwd)

# Per-submission task wrapper. As in slurm_run_sims.sh, paths are
# substituted at submit time; SLURM_ARRAY_TASK_ID expands at run time.
TASK_WRAPPER="${META_DIR}/_mosaic_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_mosaic.sh at $(date -Iseconds) for ${CONFIG} (${TAG}).
# One SLURM array task = one manifest line (line = TASK_ID + OFFSET).
set -euo pipefail
cd "${PROJ_ABS}"
LINE_NUM=\$((SLURM_ARRAY_TASK_ID + ${OFFSET}))
ASN=\$(sed -n "\${LINE_NUM}p" "${MANIFEST}")
[ -n "\$ASN" ] || { echo "empty manifest line at index \${LINE_NUM} (TASK_ID=\${SLURM_ARRAY_TASK_ID} OFFSET=${OFFSET})" >&2; exit 1; }
BASE=\$(basename "\$ASN" .json)
OUT="${MOSAIC_DIR}/\${BASE%_asn}_coadd.asdf"
LOG="${LOG_DIR}/\${BASE%_asn}_mosaic.log"
if [ -f "\$OUT" ]; then
    echo "skip (exists): \$OUT"
    exit 0
fi
exec pixi run --manifest-path "${PROJ_ABS}/pixi.toml" bash -c "strun romancal.pipeline.MosaicPipeline \"\$ASN\" --output_dir \"${MOSAIC_DIR}\" --steps.resample.in_memory=False > \"\$LOG\" 2>&1"
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --cpus-per-task=1 --mem="$MEM" --time="$TIME" \
    --array="${ARR}%${K}" --job-name=acc-mosaic \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

META="${META_DIR}/mosaic-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
cp "$MANIFEST"     "${META}.manifest"
{
    echo "JOB=$JOB"
    echo "ARRAY=$ARR"
    echo "LINE_OFFSET=$OFFSET"
    echo "MAX_CONCURRENT=$K"
    echo "PARTITION=$PART"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"
    echo "MANIFEST=$MANIFEST"
    echo "MANIFEST_LINES=$N"
    echo "GIT_COMMIT=$(git -C "$PROJ_ABS" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array ${ARR}, K=${K}, partition=${PART}, mem=${MEM})"
echo "  manifest:     ${MANIFEST} (${N} mosaics)"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler logs: ${SLURM_LOG}/${JOB}_*.out"
