#!/usr/bin/env bash
# Stage 02 SLURM driver: submit sims.script as a SLURM job array.
#
# One array task per line of ${OUTPUT_BASE}/${TAG}/sims.script. Each line is
# already a self-contained skip-if-exists shell snippet (built by
# 01_build_script.sh + _postprocess_sims.py), so the per-task body is just:
#   sed -n "${SLURM_ARRAY_TASK_ID}p" sims.script | bash
#
# Env-var hooks (all optional):
#   SUBSET            sbatch --array spec, default "1-N" where N = wc -l of sims.script
#   MAX_CONCURRENT    --array=...%K, default 80 (5 mem-lg nodes x 16 cores)
#   PARTITION         default mem-lg
#   MEM               default 8G  (measured peak RSS ~7.7 GB per worker)
#   TIME              default 30:00 (each sim ~8.5 min steady-state)
#   SKIP_CRDS_VERIFY  if set, skip pre-flight CRDS check
#
# Per-submission audit trail goes to ${OUTPUT_BASE}/${TAG}/slurm-meta/sims-<JobID>.{sh,env}.
# SLURM scheduler stdout (the thin chatter, mostly empty unless a task crashes
# before the per-sim wrapper takes over) lands at /data/npadman/tmp/slurm-logs/sims/.
#
# Usage: slurm_run_sims.sh configs/<tag>.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:?usage: $0 configs/<tag>.yaml}"
eval "$(pixi run python scripts/_config.py "$CONFIG")"

SCRIPT="${OUTPUT_BASE}/${TAG}/sims.script"
[ -f "$SCRIPT" ] || { echo "missing $SCRIPT (run 01_build_script.sh $CONFIG first)"; exit 1; }

if [ -z "${SKIP_CRDS_VERIFY:-}" ]; then
    pixi run python scripts/00_verify_crds.py
fi

N=$(wc -l < "$SCRIPT")
ARR="${SUBSET:-1-${N}}"
K="${MAX_CONCURRENT:-80}"
PART="${PARTITION:-mem-lg}"
MEM="${MEM:-8G}"
TIME="${TIME:-30:00}"

PROJ_ABS=$(pwd)
META_DIR="${OUTPUT_BASE}/${TAG}/slurm-meta"
SLURM_LOG=/data/npadman/tmp/slurm-logs/sims
mkdir -p "$META_DIR" "$SLURM_LOG"

# Per-submission wrapper: hardcodes SCRIPT + PROJ_ABS so the submitted file
# is self-contained and serves as an audit record. Backslashed $ are deferred
# to runtime (when SLURM sets SLURM_ARRAY_TASK_ID on the compute node);
# unescaped $ are expanded now at submit time.
TS=$(date +%Y%m%dT%H%M%S)
TASK_WRAPPER="${META_DIR}/_sims_array_task_${TS}.sh"
cat > "$TASK_WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by slurm_run_sims.sh at $(date -Iseconds) for ${CONFIG} (${TAG}).
# One SLURM array task = one line of sims.script.
set -euo pipefail
cd "${PROJ_ABS}"
LINE=\$(sed -n "\${SLURM_ARRAY_TASK_ID}p" "${SCRIPT}")
[ -n "\$LINE" ] || { echo "empty line at index \${SLURM_ARRAY_TASK_ID}" >&2; exit 1; }
exec pixi run --manifest-path "${PROJ_ABS}/pixi.toml" bash -c "\$LINE"
EOF
chmod +x "$TASK_WRAPPER"

JOB=$(sbatch --parsable \
    --partition="$PART" --cpus-per-task=1 --mem="$MEM" --time="$TIME" \
    --array="${ARR}%${K}" --job-name=acc-sims \
    --output="${SLURM_LOG}/%A_%a.out" \
    "$TASK_WRAPPER")

# Archive the submission record under slurm-meta/.
META="${META_DIR}/sims-${JOB}"
cp "$TASK_WRAPPER" "${META}.task.sh"
{
    echo "JOB=$JOB"
    echo "ARRAY=$ARR"
    echo "MAX_CONCURRENT=$K"
    echo "PARTITION=$PART"
    echo "MEM=$MEM"
    echo "TIME=$TIME"
    echo "CONFIG=$CONFIG"
    echo "SCRIPT=$SCRIPT"
    echo "SCRIPT_LINES=$N"
    echo "GIT_COMMIT=$(git -C "$PROJ_ABS" rev-parse HEAD 2>/dev/null || echo NA)"
    echo "SLURM_LOG_DIR=$SLURM_LOG"
    echo "SUBMITTED_AT=$(date -Iseconds)"
} > "${META}.env"

echo "submitted JobID=${JOB} (array ${ARR}, K=${K}, partition=${PART}, mem=${MEM})"
echo "  task wrapper: ${TASK_WRAPPER}"
echo "  audit:        ${META}.env"
echo "  scheduler logs: ${SLURM_LOG}/${JOB}_*.out"
echo "  monitor:      sacct -j ${JOB} --format=JobID,State,Elapsed,MaxRSS,ExitCode"
